#!/usr/bin/env python3
"""Classify dataset/*/*.mtx by predicted SpFFT host-RAM footprint.

SpFFT (single-rank) keeps a host-side complex grid for the transform plus
internal scratch. The footprint is dominated by `rows * cols * 8 bytes`,
multiplied by a safety factor that accounts for working buffers.

Usage:
    .venv/bin/python scripts/list_spfft_safe.py
    .venv/bin/python scripts/list_spfft_safe.py --max-host-gb 12
    .venv/bin/python scripts/list_spfft_safe.py \\
        --out dataset_lists/spfft_safe.txt --quiet

The output file lists one matrix path per line, suitable for piping into
`MATRIX_LIST=... ./scripts/run_sweep.sh`.
"""

import argparse
from pathlib import Path
import sys


def parse_mtx_header(path: Path):
    """Return (rows, cols, nnz) from a Matrix Market file."""
    with open(path, "r", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("%"):
                continue
            parts = line.split()
            if len(parts) >= 3:
                return int(parts[0]), int(parts[1]), int(parts[2])
    raise ValueError(f"no dimension line in {path}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dataset", default="dataset", type=Path,
                   help="Root containing one folder per matrix (default: dataset).")
    p.add_argument("--max-host-gb", type=float, default=16.0,
                   help="Cap predicted SpFFT host RAM in GB (default: 16).")
    p.add_argument("--safety-factor", type=float, default=4.0,
                   help="Multiplier on bare grid bytes — accounts for SpFFT "
                        "working buffers (default: 4).")
    p.add_argument("--out", type=Path, default=Path("dataset_lists/spfft_safe.txt"),
                   help="Where to write the safe-list (default: %(default)s).")
    p.add_argument("--quiet", action="store_true",
                   help="Skip the per-matrix table; just write the file.")
    args = p.parse_args()

    # Only consider the canonical "<dirname>/<dirname>.mtx" file. Datasets
    # often ship with sibling files (_label.mtx, _coord.mtx, _nodename.mtx)
    # that aren't the primary matrix and have no dimension header.
    matrices = sorted(
        m for m in args.dataset.glob("*/*.mtx")
        if m.stem == m.parent.name
    )
    if not matrices:
        print(f"error: no matrices under {args.dataset}/*/*.mtx", file=sys.stderr)
        sys.exit(1)

    rows = []
    for m in matrices:
        try:
            r, c, nnz = parse_mtx_header(m)
        except (ValueError, OSError) as e:
            print(f"warn: could not parse {m}: {e}", file=sys.stderr)
            continue
        area = r * c
        pred_gb = area * 8 * args.safety_factor / 1e9
        safe = pred_gb <= args.max_host_gb
        rows.append((m, m.parent.name, r, c, nnz, pred_gb, safe))

    rows.sort(key=lambda x: x[2] * x[3])

    if not args.quiet:
        print(f"Predicted SpFFT host-RAM footprint "
              f"(safety_factor={args.safety_factor}, cap={args.max_host_gb} GB)")
        print(f"{'matrix':35s} {'rows':>8s} {'cols':>8s} "
              f"{'nnz':>10s} {'pred_GB':>9s}  status")
        print("-" * 90)
        for _, name, r, c, nnz, pred_gb, safe in rows:
            status = "SAFE" if safe else "RISKY"
            print(f"{name:35s} {r:>8d} {c:>8d} {nnz:>10d} "
                  f"{pred_gb:>9.2f}  {status}")
        print()

    safe_paths = [str(m) for m, *_, safe in rows if safe]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        f.write("# Generated by scripts/list_spfft_safe.py\n")
        f.write(f"# safety_factor={args.safety_factor}  "
                f"max_host_gb={args.max_host_gb}\n")
        for path in safe_paths:
            f.write(path + "\n")

    print(f"Wrote {len(safe_paths)} SAFE / {len(rows)} total to {args.out}")


if __name__ == "__main__":
    main()
